version: '3.7'
services:
  chromedriver:
    image: blueimp/chromedriver
    init: true
    tmpfs: /tmp
    environment:
      - DISABLE_X11=false
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    volumes:
      - ./assets:/home/webdriver/assets:ro
    ports:
      - 127.0.0.1:5900:5900
  wdio:
    image: blueimp/wdio
    init: true
    read_only: true
    environment:
      - WAIT_FOR_HOSTS=
          chromedriver:4444
    volumes:
      - .:/opt:ro
      - ./reports:/opt/reports
    depends_on:
      - chromedriver